baseurl:                http://api-uat-internal.hatthabank.com/
sendotp:                notification-service/api/1.0/information/ext-notification/send
sendoob:                notification-service/api/1.0/information/ext-notification/send
inquiry_oob:            notification-service/api/1.0/confirmation/oob/inquiry
approve_oob:            notification-service/api/1.0/confirmation/oob/APPROVED
reject_oob:             notification-service/api/1.0/confirmation/oob/REJECTED
verify_phonenumber:     account-service/api/v1.0/account-opening?countryCode=855&phoneNumber=
otp_online_acc_opening:   user-profile/api/v1.0/otp/users/validate 
check_kyc:              account-service/api/v1.0/account-opening/kyc/check 
verify_kyc:             account-service/api/v1.0/account-opening/kyc/verify
create_account:         account-service/api/v1.0/account-opening/confirm
cif:                    001088774
content-Type:           application/json
Account-service:        account-service
countryCode:            '855'
phoneNumber:            '12465465'
client_id:              '12345'
client_secret:          12345_secret
x-api-key:              12345_api_key
device_id:              iOS-8C937EE8C94345DC80FF0A5C211ADECD
app_version:           '3.1.0'
language:               en
client_req_timestamp:   '1984191283000'
Os:                     ios
nid_image:              ../resources/resource/nid.jpg
user_image:             ../resources/resource/userimg.jpg
vannak_nid:             ../resources/resource/vnid.jpg
vannak_img:             ../resources/resource/vimg.jpg
test_case_counter:      '0'
verify_id_expired:      eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODU0MjgwOTcsImV4cCI6MTY4NTQyODk5Nywic2VydmljZXMiOlsidXNlci1wcm9maWxlIiwiYWNjb3VudC1zZXJ2aWNlIl0sInZhbGlkYXRlZCI6dHJ1ZSwicmVxdWVzdF9pZCI6InNjYXR3ZmVVRWVnck1oSVEiLCJkZXZpY2VfaWQiOiIxMjYwODYxOSJ9.kj1Rq4mHF7wmIw05LVWLZYYP_Z_sjmOb5BI_UxbxF35VqhWFMlrZNcU0rqCBjIs42SFQcGxW2hY7SkIuzXPr1A